### ISSUE TITLE
Incluir enlace al repositorio

### ISSUE THREAD

**Issue by danimpm** [danimpm/sueldo_trienios_consultoria#2]
Incluir un enlace a este repositorio en la web.

**Comment by zrpfpr** [comment]
Igualmente, sería recomendable mover el enlace a la web de la descripción de repositorio al fichero README.MD ya que es lo que primero se suele leer...

**Comment by danimpm** [comment]
> Igualmente, sería recomendable mover el enlace a la web de la descripción de repositorio al fichero README.MD ya que es lo que primero se suele leer...

¡Hecho!

**Comment by danimpm** [comment]
Incluido en la versión v0.0.3.
